trigger: none

pr: none

pool:
  vmImage: 'ubuntu-22.04'

variables:
  buildConfiguration: 'Release'
  workingDirectory: 'botbuilder-dotnet'

stages:
- stage: Build_Test_Pack
  jobs:
  - job: BuildTestPack
    displayName: 'Build, Test, and Pack'
    steps:
      - checkout: none
      
      - script: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git clone https://github.com/rido-min/botbuilder-dotnet.git
          cd botbuilder-dotnet
          git status
        displayName: 'Clone public GitHub repo anonymously'

      - task: UseDotNet@2
        displayName: 'Use .NET 9'
        inputs:
          packageType: 'sdk'
          version: '9.0.x'

      - script: dotnet restore Microsoft.Bot.Builder.sln
        displayName: 'Restore'
        workingDirectory: '$(workingDirectory)'

      - script: dotnet build Microsoft.Bot.Builder.sln --no-restore --configuration $(buildConfiguration)
        displayName: 'Build'
        workingDirectory: '$(workingDirectory)'
      # - script: dotnet test --no-restore --verbosity normal --logger trx --configuration $(buildConfiguration)
      #   displayName: 'Test'

      - task: DotNetCoreCLI@2
        displayName: 'Pack NuGet Packages'
        inputs:
          command: pack
          packagesToPack: '$(workingDirectory)/Microsoft.Bot.Builder.sln'
          packDirectory: '$(Build.ArtifactStagingDirectory)'
          includesymbols: false
          nobuild: true
          configuration: '$(buildConfiguration)'
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'Version'
          buildProperties: 'SymbolPackageFormat=snupkg'

      - task: NuGetCommand@2
        displayName: 'Push NuGet Packages'
        inputs:
          command: push
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: external
          publishFeedCredentials: 'Teams-Graph-Feed'
      